# Exercício

1. Crie um array NumPy unidimensional com os números de 1 a 10.
   
2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.
   
3. Crie um array NumPy bidimensional 4x4 preenchido com uns.
   
4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.
5. Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.
6. Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.
7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.
8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.
9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.
10. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.
11. Dado o array NumPy x = [1, 2, 3], crie:
    
        a) Crie um novo array com os valores de x repetidos três vezes.
        b) Crie um novo array com os valores de x repetidos lado a lado três vezes.
        c) Crie um novo array com os valores de x repetidos verticalmente três vezes.
        d) Inverta a ordem dos elementos do array.
12. Considere o seguinte array bidimensional vendas representando as vendas de produtos em diferentes regiões ao longo de 5 anos, onde cada coluna é um ano e cada linha uam região:
    
            vendas = np.array([
                [100, 150, 200, 120, 180],  # Região 1
                [80, 120, 150, 100, 130],   # Região 2
                [200, 180, 220, 190, 210],  # Região 3
                [150, 160, 170, 140, 180],  # Região 4
                [120, 110, 130, 90, 140]    # Região 5
            ])

        a) Calcule e exiba a média de vendas de cada região ao longo dos 5 anos.
        b) Determine o ano (1, 2, 3, 4 ou 5) com o maior número de vendas para cada região e exiba os anos correspondentes.
        c) Encontre e exiba a região com a menor média de vendas ao longo dos 5 anos.
        d) Crie um novo array chamado vendas_lojas, contendo apenas as vendas das lojas nos últimos dois anos.
        e) Usando o array vendas_lojas do item acima, calcule e exiba a média de vendas de cada loja nos últimos dois anos.
13. Considere o seguinte array bidimensional notas representando as notas dos alunos em diferentes disciplinas ao longo de 3 trimestres:

            notas = np.array([
                [8, 7, 6],
                [9, 8, 7],
                [6, 5, 4],
                [7, 6, 5],
                [10, 9, 8]
             ])
    
        a) Crie um novo array chamado aprovados que contenha apenas as notas dos alunos que foram aprovados em todas as disciplinas nos três trimestres (nota maior ou igual a 7).
        b) Calcule e exiba a média das notas dos alunos aprovados em cada disciplina.
        c) Determine quantos alunos foram aprovados em todas as disciplinas nos três trimestres.

In [2]:
import numpy as np

In [7]:
# 7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = A[:, 1]
print(result)

[2 5 8]


In [8]:
#8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.

x = np.array([1, 2, 3, 4, 5])
novo_x = np.where(x % 2 == 0, -1, x)
print("Array com valores pares substituídos por -1:", novo_x)

Array com valores pares substituídos por -1: [ 1 -1  3 -1  5]


In [10]:
# 9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.
x = np.array([1, 2, 3, 4, 5])
novo_x = np.where(x > 2, 0, x)
print("Array com valores maior que 2 substituídos por 0:", novo_x)

Array com valores maior que 2 substituídos por 0: [1 2 0 0 0]


In [12]:
# 10. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Multiplicação Matricial forma 1: \n",np.dot(A,B))
print("Multiplicação Matricial forma 2: \n",A.dot(B))

Multiplicação Matricial forma 1: 
 [[19 22]
 [43 50]]
Multiplicação Matricial forma 2: 
 [[19 22]
 [43 50]]


11. Dado o array NumPy x = [1, 2, 3], crie:
    
        a) Crie um novo array com os valores de x repetidos três vezes.
        b) Crie um novo array com os valores de x repetidos lado a lado três vezes.
        c) Crie um novo array com os valores de x repetidos verticalmente três vezes.
        d) Inverta a ordem dos elementos do array.

In [24]:
x = np.array([1, 2, 3])

resultA = np.tile(x,3)
resultB = np.repeat(x,3)
resultC = np.tile(x,(3,1))
resultD = np.flip(x)

print("resposta item a: ", resultA)
print("resposta item b: ", resultB)
print("resposta item c:\n", resultC)
print("resposta item d: ", resultD)


resposta item a:  [1 2 3 1 2 3 1 2 3]
resposta item b:  [1 1 1 2 2 2 3 3 3]
resposta item c:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
resposta item d:  [3 2 1]


12. Considere o seguinte array bidimensional vendas representando as vendas de produtos em diferentes regiões ao longo de 5 anos, onde cada coluna é um ano e cada linha uam região:
    
            vendas = np.array([
                [100, 150, 200, 120, 180],  # Região 1
                [80, 120, 150, 100, 130],   # Região 2
                [200, 180, 220, 190, 210],  # Região 3
                [150, 160, 170, 140, 180],  # Região 4
                [120, 110, 130, 90, 140]    # Região 5
            ])

        a) Calcule e exiba a média de vendas de cada região ao longo dos 5 anos.
        b) Determine o ano (1, 2, 3, 4 ou 5) com o maior número de vendas para cada região e exiba os anos correspondentes.
        c) Encontre e exiba a região com a menor média de vendas ao longo dos 5 anos.
        d) Crie um novo array chamado vendas_lojas, contendo apenas as vendas das lojas nos últimos dois anos.
        e) Usando o array vendas_lojas do item acima, calcule e exiba a média de vendas de cada loja nos últimos dois anos.

In [63]:
vendas = np.array([
                [100, 150, 200, 120, 180],  # Região 1
                [80, 120, 150, 100, 130],   # Região 2
                [200, 180, 220, 190, 210],  # Região 3
                [150, 160, 170, 140, 180],  # Região 4
                [120, 110, 130, 90, 140]    # Região 5
            ])


media_regiao = np.mean(vendas, axis=1)
print("a) medias por regiões: ",media_regiao)

print("\nb) Ano com o maior número de vendas para cada região:")
for i in range(len(vendas)):
    ano_maior_vendas = np.argmax(vendas[i]) + 1  # Adicionando 1 pois os anos começam de 1
    print(f"Região {i+1}: Ano {ano_maior_vendas}")

mediaRegioes = [venda.mean() for venda in vendas]
menorValorRegiao = np.array(mediaRegioes).min()
minRegiao = np.argmin(mediaRegioes) + 1
print("\nc) região {} tem o menor valor:{} ".format(minRegiao,menorValorRegiao))

vendas_lojas = vendas

print("\nd)Vendas nos ultimos dois anos:\n",vendas_lojas)


media_vendas_lojas = np.mean(vendas_lojas, axis=1)
print("\ne) Média de vendas de cada loja nos últimos dois anos:", media_vendas_lojas)

a) medias por regiões:  [150. 116. 200. 160. 118.]

b) Ano com o maior número de vendas para cada região:
Região 1: Ano 3
Região 2: Ano 3
Região 3: Ano 3
Região 4: Ano 5
Região 5: Ano 5

c) região 2 tem o menor valor:116.0 

d)Vendas nos ultimos dois anos:
 [[100 150 200 120 180]
 [ 80 120 150 100 130]
 [200 180 220 190 210]
 [150 160 170 140 180]
 [120 110 130  90 140]]

e) Média de vendas de cada loja nos últimos dois anos: [150. 116. 200. 160. 118.]


13. Considere o seguinte array bidimensional notas representando as notas dos alunos em diferentes disciplinas ao longo de 3 trimestres:

            notas = np.array([
                [8, 7, 6],
                [9, 8, 7],
                [6, 5, 4],
                [7, 6, 5],
                [10, 9, 8]
             ])
    
        a) Crie um novo array chamado aprovados que contenha apenas as notas dos alunos que foram aprovados em todas as disciplinas nos três trimestres (nota maior ou igual a 7).
        b) Calcule e exiba a média das notas dos alunos aprovados em cada disciplina.
        c) Determine quantos alunos foram aprovados em todas as disciplinas nos três trimestres.

In [66]:
notas = np.array([
    [8, 7, 6],
    [9, 8, 7],
    [6, 5, 4],
    [7, 6, 5],
    [10, 9, 8]
])

aprovados = notas[(notas >= 7).all(axis=1)]
media_aprovados = np.mean(aprovados, axis=0)
quantidade_aprovados = len(aprovados)

print(notas)
print("\na) Notas dos alunos aprovados em todas as disciplinas:\n", aprovados)
print("b) Média das notas dos alunos aprovados em cada disciplina:", media_aprovados)
print("c) Quantidade de alunos aprovados em todas as disciplinas:", quantidade_aprovados)


[[ 8  7  6]
 [ 9  8  7]
 [ 6  5  4]
 [ 7  6  5]
 [10  9  8]]

a) Notas dos alunos aprovados em todas as disciplinas:
 [[ 9  8  7]
 [10  9  8]]
b) Média das notas dos alunos aprovados em cada disciplina: [9.5 8.5 7.5]
c) Quantidade de alunos aprovados em todas as disciplinas: 2
