# Exercício

1. Crie um array NumPy unidimensional com os números de 1 a 10.
   
2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.
   
3. Crie um array NumPy bidimensional 4x4 preenchido com uns.
   
4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.
5. Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.
6. Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.
7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.
8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.
9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.
10. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.
11. Dado o array NumPy x = [1, 2, 3], crie:
    
        a) Crie um novo array com os valores de x repetidos três vezes.
        b) Crie um novo array com os valores de x repetidos lado a lado três vezes.
        c) Crie um novo array com os valores de x repetidos verticalmente três vezes.
        d) Inverta a ordem dos elementos do array.
12. Considere o seguinte array bidimensional vendas representando as vendas de produtos em diferentes regiões ao longo de 5 anos, onde cada coluna é um ano e cada linha uam região:
    
            vendas = np.array([
                [100, 150, 200, 120, 180],  # Região 1
                [80, 120, 150, 100, 130],   # Região 2
                [200, 180, 220, 190, 210],  # Região 3
                [150, 160, 170, 140, 180],  # Região 4
                [120, 110, 130, 90, 140]    # Região 5
            ])

        a) Calcule e exiba a média de vendas de cada região ao longo dos 5 anos.
        b) Determine o ano (1, 2, 3, 4 ou 5) com o maior número de vendas para cada região e exiba os anos correspondentes.
        c) Encontre e exiba a região com a menor média de vendas ao longo dos 5 anos.
        d) Crie um novo array chamado vendas_lojas, contendo apenas as vendas das lojas nos últimos dois anos.
        e) Usando o array vendas_lojas do item acima, calcule e exiba a média de vendas de cada loja nos últimos dois anos.
13. Considere o seguinte array bidimensional notas representando as notas dos alunos em diferentes disciplinas ao longo de 3 trimestres:

            notas = np.array([
                [8, 7, 6],
                [9, 8, 7],
                [6, 5, 4],
                [7, 6, 5],
                [10, 9, 8]
             ])
    
        a) Crie um novo array chamado aprovados que contenha apenas as notas dos alunos que foram aprovados em todas as disciplinas nos três trimestres (nota maior ou igual a 7).
        b) Calcule e exiba a média das notas dos alunos aprovados em cada disciplina.
        c) Determine quantos alunos foram aprovados em todas as disciplinas nos três trimestres.

In [2]:
import numpy as np

In [5]:
# 1. Crie um array NumPy unidimensional com os números de 1 a 10.
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# 2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.

e2 = np.zeros([3,3])
e2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#3. Crie um array NumPy bidimensional 4x4 preenchido com uns.

e3 = np.ones([4,4])
e3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
#4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.

e4 = np.random.random((20,))

e42 = np.linspace(0,100,20)

print(e4)
print(e42)

[0.05484287 0.71398392 0.76135811 0.01833216 0.57356264 0.49126673
 0.53678442 0.62622493 0.05273971 0.4569879  0.72396334 0.04351858
 0.2353036  0.28423165 0.68860699 0.40756524 0.83986764 0.49135816
 0.14742037 0.70860948]
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [33]:
e = np.array([1,2,3,4])
e.shape

(4,)

In [41]:
#5. Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.
e5 = np.arange(0,10,0.5)
e5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [55]:
# 6. Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.
np.random.randint(100,size=(5,5))

array([[ 5, 96, 54, 69, 94],
       [61, 48, 25, 17,  8],
       [70, 35, 74, 46, 68],
       [99, 25, 85, 15, 69],
       [41, 73, 23, 66, 77]])

In [68]:
# 7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A,"\n")

print(A[:,2],"\n")
print(A[:,-1],"\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[3 6 9] 

[3 6 9] 



In [75]:
#8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.
x = np.array([1, 2, 3, 4, 5])
x[x%2 == 0] = -1
x

array([ 1, -1,  3, -1,  5])

In [76]:
#9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.
x = np.array([1, 2, 3, 4, 5])
x[x > 2] = 0
x

array([1, 2, 0, 0, 0])

In [79]:
#10. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A.dot(B))
print(np.dot(A,B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [91]:
#11. Dado o array NumPy x = [1, 2, 3], crie:    
    # a) Crie um novo array com os valores de x repetidos três vezes.
    # b) Crie um novo array com os valores de x repetidos lado a lado três vezes.
    # c) Crie um novo array com os valores de x repetidos verticalmente três vezes.
    # d) Inverta a ordem dos elementos do array.


x = np.array([1, 2, 3])
print("a: ", x ** 3)
print("b: ", np.repeat(x,3))
print("c: ", np.repeat(x,3).reshape(3,3).T)
print("c: ", np.tile(x,(3,1)))
print("d: ", np.flip(x))


a:  [ 1  8 27]
b:  [1 1 1 2 2 2 3 3 3]
c:  [[1 2 3]
 [1 2 3]
 [1 2 3]]
c:  [[1 2 3]
 [1 2 3]
 [1 2 3]]
d:  [3 2 1]


12. Considere o seguinte array bidimensional vendas representando as vendas de produtos em diferentes regiões ao longo de 5 anos, onde cada coluna é um ano e cada linha uam região:
    
            vendas = np.array([
                [100, 150, 200, 120, 180],  # Região 1
                [80, 120, 150, 100, 130],   # Região 2
                [200, 180, 220, 190, 210],  # Região 3
                [150, 160, 170, 140, 180],  # Região 4
                [120, 110, 130, 90, 140]    # Região 5
            ])

        a) Calcule e exiba a média de vendas de cada região ao longo dos 5 anos.
        b) Determine o ano (1, 2, 3, 4 ou 5) com o maior número de vendas para cada região e exiba os anos correspondentes.
        c) Encontre e exiba a região com a menor média de vendas ao longo dos 5 anos.
        d) Crie um novo array chamado vendas_lojas, contendo apenas as vendas das lojas nos últimos dois anos.
        e) Usando o array vendas_lojas do item acima, calcule e exiba a média de vendas de cada loja nos últimos dois anos.

In [47]:
vendas = np.array([
                [100, 150, 200, 120, 180],  
                [80, 120, 150, 100, 130],   
                [200, 180, 220, 190, 210],  
                [150, 160, 170, 140, 180],  
                [120, 110, 130, 90, 140]    
            ])

a = "média da regiao 1 {}, media da regiao 2 {}, media da regiao 3 {}"\
        .format(sum(vendas[0]),sum(vendas[1]),sum(vendas[2]))


print("a: ",a)
print("b: ")
for i in range(len(vendas)): print("região {}, valor: {} e indeice {}".format(i,vendas[i].max(),np.argmax(vendas[i])) )

arrayMedias  = np.array([ np.mean(vendas[i]) for i in range(len(vendas))])
print("\nc: ","menor media: {} e região: {}".format( arrayMedias.min(),np.argmin(arrayMedias)) )
vendas_lojas = vendas[::,3:]
print("\ne: ultumas vendas:\n ",vendas_lojas)
arrayMedias  = np.array([ np.mean(vendas_lojas[i]) for i in range(len(vendas_lojas))])
print("\ne: ","menor media: {} e região: {}".format( arrayMedias.min(),np.argmin(arrayMedias)) )


a:  média da regiao 1 750, media da regiao 2 580, media da regiao 3 1000
b: 
região 0, valor: 200 e indeice 2
região 1, valor: 150 e indeice 2
região 2, valor: 220 e indeice 2
região 3, valor: 180 e indeice 4
região 4, valor: 140 e indeice 4

c:  menor media: 116.0 e região: 1

e: ultumas vendas:
  [[120 180]
 [100 130]
 [190 210]
 [140 180]
 [ 90 140]]

e:  menor media: 115.0 e região: 1


In [42]:
vendas_lojas = vendas[::,3:]
print(vendas)
print()
print(vendas_lojas)

[[100 150 200 120 180]
 [ 80 120 150 100 130]
 [200 180 220 190 210]
 [150 160 170 140 180]
 [120 110 130  90 140]]

[[120 180]
 [100 130]
 [190 210]
 [140 180]
 [ 90 140]]


13. Considere o seguinte array bidimensional notas representando as notas dos alunos em diferentes disciplinas ao longo de 3 trimestres:

            notas = np.array([
                [8, 7, 6],
                [9, 8, 7],
                [6, 5, 4],
                [7, 6, 5],
                [10, 9, 8]
             ])
    
        a) Crie um novo array chamado aprovados que contenha apenas as notas dos alunos que foram aprovados em todas as disciplinas nos três trimestres (nota maior ou igual a 7).
        b) Calcule e exiba a média das notas dos alunos aprovados em cada disciplina.
        c) Determine quantos alunos foram aprovados em todas as disciplinas nos três trimestres.

In [51]:
notas = np.array([
                [8, 7, 6],
                [9, 8, 7],
                [6, 5, 4],
                [7, 6, 5],
                [10, 9, 8]
             ])

aprovados = notas[notas>=7]
print("a: Aprovados: ",aprovados)
print("b: \n")
for i in range(len(notas)) : print("Media: {} do aluno: {} ".format(notas[i].min(), i))


result  = [ len(sub[sub>7]) for sub in notas]
result = np.array(result)

print("c: ", result )


a: Aprovados:  [ 8  7  9  8  7  7 10  9  8]
Media: 6 do aluno: 0 
Media: 7 do aluno: 1 
Media: 4 do aluno: 2 
Media: 5 do aluno: 3 
Media: 8 do aluno: 4 


In [60]:
result  = [ len(sub[sub>7]) for sub in notas]
result = np.array(result)
np.count_nonzero(result)

3